version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant123
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: