ALTER TABLE "Food" ADD COLUMN "isAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FoodOption" ADD COLUMN "isAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OptionChoice" ADD COLUMN "isAvailable" BOOLEAN NOT NULL DEFAULT true;
